import React, { useState } from 'react';
import {
  View, Text, TouchableOpacity, ScrollView,
  StyleSheet, ActivityIndicator, RefreshControl, Share, Alert,
} from 'react-native';
import { useRouter } from 'expo-router';
import { useInfiniteQuery } from '@tanstack/react-query';
import { Ionicons } from '@expo/vector-icons';
import { useTheme } from '../../src/hooks/useTheme';
import { FontSize, Radius, Shadow } from '../../src/theme';
import { useInventoryStore } from '../../src/store/useAppStore';
import { getSales, getSalesPage, type InventorySale } from '../../src/services/inventoryService';
import ErrorBanner from '../../src/components/ErrorBanner';
import { exportCsv, exportPdf } from '../../src/utils/exportUtils';

const INV = '#E65100';

function buildReceiptText(sale: InventorySale, businessName: string): string {
  const lines: string[] = [];
  lines.push(`🧾 *${businessName || 'Sales Receipt'}*`);
  lines.push(`Date: ${new Date(sale.sold_at).toLocaleDateString('en-NG', { day: 'numeric', month: 'short', year: 'numeric' })}`);
  if (sale.customer_name) lines.push(`Customer: ${sale.customer_name}`);
  lines.push('');
  lines.push('*Items:*');
  sale.items.forEach(item => {
    lines.push(`• ${item.product_name} × ${item.quantity}  →  ₦${Number(item.subtotal).toLocaleString()}`);
  });
  lines.push('');
  lines.push(`*Total: ₦${Number(sale.total).toLocaleString()}*`);
  if (sale.notes) lines.push(`\nNote: ${sale.notes}`);
  lines.push('\n_Thank you for your purchase!_');
  return lines.join('\n');
}

export default function SalesHistoryScreen() {
  const { colors } = useTheme();
  const router = useRouter();
  const businessName = useInventoryStore(s => s.selectedBusinessName) ?? 'My Store';

  const {
    data, isLoading, isError, error, isRefetching, refetch,
    fetchNextPage, hasNextPage, isFetchingNextPage,
  } = useInfiniteQuery({
    queryKey: ['inventory-sales'],
    queryFn: ({ pageParam }) => getSalesPage(pageParam as string | null),
    initialPageParam: null as string | null,
    getNextPageParam: (lastPage) => lastPage.next ?? undefined,
  });

  const sales = data?.pages.flatMap(p => p.results) ?? [];
  const totalCount = data?.pages[0]?.count ?? 0;

  const [expanded, setExpanded] = useState<number | null>(null);

  const handleExportCsv = async () => {
    try {
      const all = await getSales(); // fetch all records for export
      const headers = ['Date', 'Customer', 'Items', 'Total (NGN)'];
      const rows = all.map(s => [
        new Date(s.sold_at).toLocaleDateString('en-NG'),
        s.customer_name ?? 'Walk-in',
        s.items.map(i => `${i.product_name} x${i.quantity}`).join('; '),
        parseFloat(s.total).toFixed(2),
      ]);
      await exportCsv('ajo-sales.csv', headers, rows);
    } catch {
      Alert.alert('Export failed', 'Could not export sales. Please try again.');
    }
  };

  const handleExportPdf = async () => {
    try {
      const all = await getSales(); // fetch all records for export
      const rowsHtml = all.map(s => {
        const date = new Date(s.sold_at).toLocaleDateString('en-NG', { day: 'numeric', month: 'short', year: 'numeric' });
        const items = s.items.map(i => `${i.product_name} ×${i.quantity}`).join(', ');
        return `<tr>
          <td>${date}</td>
          <td>${s.customer_name ?? 'Walk-in'}</td>
          <td>${items}</td>
          <td style="text-align:right">&#8358;${Number(s.total).toLocaleString()}</td>
        </tr>`;
      }).join('');
      const html = `<html><body style="font-family:Arial,sans-serif;padding:24px">
        <h2 style="color:#E65100">Ajo Sales History</h2>
        <p>Total revenue: <strong>&#8358;${totalRevenue.toLocaleString()}</strong> &nbsp;|&nbsp; Transactions: ${all.length}</p>
        <table border="1" cellpadding="8" cellspacing="0" width="100%" style="border-collapse:collapse;font-size:13px">
          <tr style="background:#E65100;color:#fff"><th>Date</th><th>Customer</th><th>Items</th><th>Total</th></tr>
          ${rowsHtml}
        </table>
        <p style="margin-top:16px;font-size:11px;color:#888">Generated by Ajo</p>
      </body></html>`;
      await exportPdf('Ajo Sales', html);
    } catch {
      Alert.alert('Export failed', 'Could not export sales. Please try again.');
    }
  };

  const promptExport = () => {
    if (totalCount === 0) {
      Alert.alert('Nothing to export', 'Record some sales first.');
      return;
    }
    Alert.alert('Export Sales', 'Choose a format', [
      { text: 'CSV (Excel / Sheets)', onPress: handleExportCsv },
      { text: 'PDF', onPress: handleExportPdf },
      { text: 'Cancel', style: 'cancel' },
    ]);
  };

  const shareReceipt = async (sale: InventorySale) => {
    const text = buildReceiptText(sale, businessName);
    try {
      await Share.share({ message: text });
    } catch {
      Alert.alert('Error', 'Could not share receipt.');
    }
  };

  const totalRevenue = sales.reduce((s, sale) => s + parseFloat(sale.total), 0);

  return (
    <View style={{ flex: 1, backgroundColor: colors.background }}>
      <View style={[s.header, { backgroundColor: colors.surface, borderBottomColor: colors.border }]}>
        <TouchableOpacity onPress={() => router.back()} hitSlop={{ top: 10, left: 10, bottom: 10, right: 10 }} accessibilityRole="button" accessibilityLabel="Go back">
          <Ionicons name="arrow-back" size={24} color={colors.textPrimary} />
        </TouchableOpacity>
        <View style={{ flex: 1, marginLeft: 16 }}>
          <Text style={{ fontSize: FontSize.lg, fontWeight: '800', color: colors.textPrimary }} accessibilityRole="header">Sales History</Text>
          <Text style={{ fontSize: FontSize.xs, color: colors.textSecondary, marginTop: 2 }}>
            {totalCount > 0 ? `${totalCount} transactions` : `${sales.length} transactions`} · ₦{totalRevenue.toLocaleString()} loaded
          </Text>
        </View>
        <TouchableOpacity onPress={promptExport} hitSlop={{ top: 8, left: 8, bottom: 8, right: 8 }} style={{ marginRight: 12 }} accessibilityRole="button" accessibilityLabel="Export sales">
          <Ionicons name="download-outline" size={22} color={INV} />
        </TouchableOpacity>
        <TouchableOpacity
          onPress={() => router.push('/inventory/new-sale' as any)}
          style={[s.addBtn, { backgroundColor: INV }]}
          accessibilityRole="button" accessibilityLabel="Record new sale"
        >
          <Ionicons name="add" size={20} color="#fff" />
        </TouchableOpacity>
      </View>

      {isLoading ? (
        <View style={{ flex: 1, alignItems: 'center', justifyContent: 'center' }}>
          <ActivityIndicator size="large" color={INV} />
        </View>
      ) : (
        <ScrollView
          contentContainerStyle={{ padding: 16, paddingBottom: 60 }}
          refreshControl={<RefreshControl refreshing={isRefetching} onRefresh={refetch} tintColor={INV} />}
          showsVerticalScrollIndicator={false}
        >
          {isError && <ErrorBanner error={error} onRetry={refetch} />}
          {sales.length === 0 ? (
            <View style={{ alignItems: 'center', paddingVertical: 48 }}>
              <Ionicons name="cart-outline" size={56} color={colors.textTertiary} />
              <Text style={{ fontSize: FontSize.md, fontWeight: '700', color: colors.textPrimary, marginTop: 14 }}>No sales yet</Text>
              <Text style={{ fontSize: FontSize.sm, color: colors.textSecondary, marginTop: 6, textAlign: 'center' }}>
                Record your first sale to start tracking revenue.
              </Text>
              <TouchableOpacity
                onPress={() => router.push('/inventory/new-sale' as any)}
                style={[s.emptyBtn, { backgroundColor: INV }]}
                accessibilityRole="button" accessibilityLabel="Record new sale"
              >
                <Text style={{ color: '#fff', fontWeight: '800', fontSize: FontSize.sm }}>Record Sale</Text>
              </TouchableOpacity>
            </View>
          ) : (
            <>
            {sales.map((sale) => {
              const isOpen = expanded === sale.id;
              const date = new Date(sale.sold_at);
              return (
                <View key={sale.id} style={[s.card, { backgroundColor: colors.surface, ...Shadow.card(colors.black) }]}>
                  {/* Summary row */}
                  <TouchableOpacity
                    onPress={() => setExpanded(isOpen ? null : sale.id)}
                    activeOpacity={0.8}
                    style={s.cardTop}
                    accessibilityRole="button"
                    accessibilityLabel={`Sale of ₦${Number(sale.total).toLocaleString()} on ${date.toLocaleDateString('en-NG', { day: 'numeric', month: 'short', year: 'numeric' })}`}
                  >
                    <View style={[s.dateBadge, { backgroundColor: '#FFF3E0' }]}>
                      <Text style={{ fontSize: FontSize.xs, fontWeight: '800', color: INV }}>
                        {date.getDate()}
                      </Text>
                      <Text style={{ fontSize: 9, fontWeight: '600', color: INV }}>
                        {date.toLocaleString('en-NG', { month: 'short' }).toUpperCase()}
                      </Text>
                    </View>
                    <View style={{ flex: 1, marginLeft: 12 }}>
                      <Text style={{ fontSize: FontSize.sm, fontWeight: '700', color: colors.textPrimary }}>
                        {sale.customer_name ?? 'Walk-in customer'}
                      </Text>
                      <Text style={{ fontSize: FontSize.xs, color: colors.textSecondary, marginTop: 2 }}>
                        {sale.items.length} item{sale.items.length !== 1 ? 's' : ''} · {date.toLocaleTimeString('en-NG', { hour: '2-digit', minute: '2-digit' })}
                      </Text>
                    </View>
                    <View style={{ alignItems: 'flex-end' }}>
                      <Text style={{ fontSize: FontSize.sm, fontWeight: '800', color: colors.textPrimary }}>
                        ₦{Number(sale.total).toLocaleString()}
                      </Text>
                      <Ionicons name={isOpen ? 'chevron-up' : 'chevron-down'} size={14} color={colors.textTertiary} style={{ marginTop: 4 }} />
                    </View>
                  </TouchableOpacity>

                  {/* Expanded items */}
                  {isOpen && (
                    <View style={{ marginTop: 12, borderTopWidth: 1, borderTopColor: colors.border, paddingTop: 12 }}>
                      {sale.items.map((item, i) => (
                        <View key={i} style={{ flexDirection: 'row', justifyContent: 'space-between', marginBottom: 6 }}>
                          <Text style={{ fontSize: FontSize.xs, color: colors.textSecondary, flex: 1 }}>
                            {item.product_name} × {item.quantity} @ ₦{Number(item.unit_price).toLocaleString()}
                          </Text>
                          <Text style={{ fontSize: FontSize.xs, fontWeight: '700', color: colors.textPrimary }}>
                            ₦{Number(item.subtotal).toLocaleString()}
                          </Text>
                        </View>
                      ))}
                      {!!sale.notes && (
                        <Text style={{ fontSize: FontSize.xs, color: colors.textSecondary, marginTop: 6, fontStyle: 'italic' }}>
                          Note: {sale.notes}
                        </Text>
                      )}
                      <TouchableOpacity
                        onPress={() => shareReceipt(sale)}
                        style={[s.shareBtn, { borderColor: INV }]}
                        activeOpacity={0.8}
                        accessibilityRole="button" accessibilityLabel="Share receipt via WhatsApp"
                      >
                        <Ionicons name="share-social-outline" size={16} color={INV} />
                        <Text style={{ color: INV, fontWeight: '700', fontSize: FontSize.xs, marginLeft: 6 }}>
                          Share Receipt (WhatsApp)
                        </Text>
                      </TouchableOpacity>
                    </View>
                  )}
                </View>
              );
            })}
            {hasNextPage && (
              <TouchableOpacity
                onPress={() => fetchNextPage()}
                disabled={isFetchingNextPage}
                style={{ alignItems: 'center', paddingVertical: 20 }}
                accessibilityRole="button"
                accessibilityLabel="Load more sales"
              >
                {isFetchingNextPage
                  ? <ActivityIndicator color={INV} />
                  : <Text style={{ color: INV, fontWeight: '700', fontSize: FontSize.sm }}>Load More</Text>
                }
              </TouchableOpacity>
            )}
            </>
          )}
        </ScrollView>
      )}
    </View>
  );
}

const s = StyleSheet.create({
  header: {
    flexDirection: 'row', alignItems: 'center',
    paddingHorizontal: 20, paddingTop: 56, paddingBottom: 18, borderBottomWidth: 1,
  },
  addBtn: { width: 36, height: 36, borderRadius: 18, alignItems: 'center', justifyContent: 'center' },
  card: { borderRadius: Radius.lg, padding: 14, marginBottom: 10 },
  cardTop: { flexDirection: 'row', alignItems: 'center' },
  dateBadge: {
    width: 42, height: 42, borderRadius: 8,
    alignItems: 'center', justifyContent: 'center',
  },
  shareBtn: {
    flexDirection: 'row', alignItems: 'center', justifyContent: 'center',
    borderWidth: 1.5, borderRadius: Radius.md,
    paddingVertical: 10, marginTop: 10,
  },
  emptyBtn: {
    marginTop: 20, paddingHorizontal: 24, paddingVertical: 12,
    borderRadius: Radius.lg,
  },
});
